### PR TITLE
Updated To Python

### PR DESCRIPTION
**Pull request by Learn-Termux**

### CODE REVIEW

**Comment by Yisus7u7** [comment]
There are changes to be corrected, one of them, is that the file with the icons and themes must be unzipped in $HOME

**Comment by Yisus7u7** [comment]
Okey, now it would be good for you to try the script. 

I can't because I have my termux busy with important files.

**Comment by Learn-Termux** [comment]
I Tried And Installed  Many times the desktop Without Any Errors.

**Comment by Yisus7u7** [comment]
Ok, I will trust that.

Update the installation steps in the README to merge the changes

**Comment by Learn-Termux** [comment]
> Ok, I will trust that.
> 
> Update the installation steps in the README to merge the changes

It doesn't need any changes on README

**Pull request merged**
