### PR TITLE
Added startdesk & stopdesk

### PR DESCRIPTION
**Pull request by ayesumit**
Better than vncserver -kill :1
start and Stop Desk..

### CODE REVIEW

**Comment by Yisus7u7** [comment]
@ayesumit 
The file already exists, it is called : 

startdesktop

**Comment by ayesumit** [comment]
I know and I added stopdesk

**Comment by Yisus7u7** [comment]
Well, specify in the install file the stopdesktop installation, in $PREFIX/bin after that it will be merged

**Comment by Yisus7u7** [comment]
@ayesumit
Ps: Rename stopdesk to stopdesktop

**Comment by ayesumit** [comment]
Done ! Now You Can View And Merge..

**Pull request merged**
